version: '3.8'
services:
  nginx-video:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    environment:
      - VIDEO_SRC=http://localhost:8888/livestream
    networks:
      - mynetwork

networks:
  mynetwork:
