version: '3.8'

services:
  server:
    container_name: mediamtx
    image: bluenviron/mediamtx:0.23.8
    #network_mode: "host"
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8000:8000"
      - "8001:8001"
      - "8189:8189"
    #volumes:
    #  - ./hls:/tmp # Mount a local 'hls' folder to '/tmp' inside the container for HLS segments

