version: '3.8'

services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935" # RTMP port
      - "8080:80"   # HTTP port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/tmp/data

  hls-server:
    image: nginx
    ports:
      - "8081:80" # HLS HTTP port
    volumes:
      - ./hls:/usr/share/nginx/html
